CREATE SCHEMA EC1_CC1N;
USE EC1_CC1N;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL);

#CRIANDO A TABELINHA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL, #NOSSA CHAVE ESTRANGEIRA DE FORNECEDOR
#CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
#RESTRIÇÃO APELIDO CH.ESTRANGEIRA(CAMPO CRIADO) REFERENCIA TABELA(CH.PRIMÁRIA)
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA PRÁTICA
REFERENCES FORNECEDORES(FORNEC_COD) #REFERENCIA A CHAVE PRIMÁRIA DE FORNECEDORES
);

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS,PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS)
REFERENCES PRODUTOS(PROD_COD));

-- DDL'S PARA TABELA DE FORNECEDORES
ALTER TABLE FORNECEDORES ADD COLUMN FORNEC_CNPJ VARCHAR(18) COMMENT 'CNPJ DO FORNECEDOR';
ALTER TABLE FORNECEDORES CHANGE FORNEC_NOME FORNEC_NOME VARCHAR(100) NOT NULL COMMENT 'NOME DO FORNECEDOR';
ALTER TABLE FORNECEDORES MODIFY FORNEC_TELEFONE VARCHAR(20) COMMENT 'TELEFONE DO FORNECEDOR';
ALTER TABLE FORNECEDORES DROP COLUMN FORNEC_CONTATO COMMENT 'REMOVE A COLUNA DE CONTATO DO FORNECEDOR';

-- DDL'S PARA TABELA DE FILIAIS
ALTER TABLE FILIAIS ADD COLUMN FILIAL_EMAIL VARCHAR(100) COMMENT 'EMAIL DE CONTATO DA FILIAL';
ALTER TABLE FILIAIS CHANGE FILIAL_RUA FILIAL_RUA VARCHAR(150) NOT NULL COMMENT 'NOME DA RUA DA FILIAL';
ALTER TABLE FILIAIS MODIFY FILIAL_CAPACIDADE DECIMAL(12,2) COMMENT 'CAPACIDADE DA FILIAL EM UNIDADES';
ALTER TABLE FILIAIS DROP COLUMN FILIAL_PAIS COMMENT 'REMOVE A COLUNA DE PAÍS DA FILIAL';

-- DDL'S PARA TABELA DE PRODUTOS
ALTER TABLE PRODUTOS ADD COLUMN PROD_VALIDADE DATE COMMENT 'DATA DE VALIDADE DO PRODUTO';
ALTER TABLE PRODUTOS CHANGE PROD_DESCRICAO PROD_DESCRICAO TEXT NOT NULL COMMENT 'DESCRIÇÃO COMPLETA DO PRODUTO';
ALTER TABLE PRODUTOS MODIFY PROD_PRECOUNIT DECIMAL(10,4) NOT NULL COMMENT 'PREÇO UNITÁRIO DO PRODUTO';
ALTER TABLE PRODUTOS DROP COLUMN PROD_UNIDMEDIDA COMMENT 'REMOVE A COLUNA DE UNIDADE DE MEDIDA DO PRODUTO';

-- DDL'S PARA TABELA DE PEDIDOS
ALTER TABLE PEDIDOS ADD COLUMN PED_OBSERVACOES TEXT COMMENT 'OBSERVAÇÕES ADICIONAIS SOBRE O PEDIDO';
ALTER TABLE PEDIDOS CHANGE PED_STATUS PED_STATUS ENUM('PENDENTE', 'CONCLUÍDO', 'EM ESPERA', 'CANCELADO') COMMENT 'STATUS DO PEDIDO (INCLUINDO CANCELADO)';
ALTER TABLE PEDIDOS MODIFY PED_HORA TIME NOT NULL COMMENT 'HORA DO PEDIDO';
ALTER TABLE PEDIDOS DROP COLUMN PED_PREVISAO COMMENT 'REMOVE A COLUNA DE PREVISÃO DO PEDIDO';

-- DDL'S PARA TABELA DE RECEBIMENTOS
ALTER TABLE RECEBIMENTOS ADD COLUMN RECEB_FORNECEDOR INT NOT NULL COMMENT 'CÓDIGO DO FORNECEDOR NO RECEBIMENTO';
ALTER TABLE RECEBIMENTOS CHANGE RECEB_HORA RECEB_HORA TIME NOT NULL COMMENT 'HORA DO RECEBIMENTO';
ALTER TABLE RECEBIMENTOS MODIFY RECEB_QUANT_PROD DECIMAL(10,3) COMMENT 'QUANTIDADE DE PRODUTO RECEBIDO';
ALTER TABLE RECEBIMENTOS DROP COLUMN RECEB_PEDIDOS COMMENT 'REMOVE A COLUNA DE PEDIDOS DO RECEBIMENTO';

-- DDL'S PARA TABELA DE PEDIDOS_PRODUTOS
ALTER TABLE PEDIDOS_PRODUTOS ADD COLUMN PDPR_PRECO_UNITARIO DECIMAL(10,2) NOT NULL COMMENT 'PREÇO UNITÁRIO DO PRODUTO NO PEDIDO';
ALTER TABLE PEDIDOS_PRODUTOS CHANGE PDPR_QUANT PDPR_QUANT DECIMAL(10,3) NOT NULL COMMENT 'QUANTIDADE DO PRODUTO NO PEDIDO';
ALTER TABLE PEDIDOS_PRODUTOS MODIFY PDPR_PEDIDOS INT NOT NULL COMMENT 'CÓDIGO DO PEDIDO NO RELACIONAMENTO';
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN PDPR_PRODUTOS COMMENT 'REMOVE O RELACIONAMENTO DIRETO COM PRODUTOS DA TABELA';

-- DDL'S PARA TABELA DE FILIAIS_PRODUTOS
ALTER TABLE FILIAIS_PRODUTOS ADD COLUMN FLPR_LOCALIZACAO VARCHAR(100) COMMENT 'LOCALIZAÇÃO DO PRODUTO NA FILIAL';
ALTER TABLE FILIAIS_PRODUTOS CHANGE FLPR_QUANT FLPR_QUANT DECIMAL(10,3) COMMENT 'QUANTIDADE DO PRODUTO NA FILIAL';
ALTER TABLE FILIAIS_PRODUTOS MODIFY FLPR_FILIAL INT NOT NULL COMMENT 'CÓDIGO DA FILIAL NO RELACIONAMENTO';
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN FLPR_PRODUTOS COMMENT 'REMOVE O RELACIONAMENTO DIRETO COM PRODUTOS DA FILIAL';

-- DDL'S PARA TABELA DE FORNECEDORES_PRODUTOS
ALTER TABLE FORNECEDORES_PRODUTOS ADD COLUMN FRPR_VALIDADE DATE COMMENT 'DATA DE VALIDADE DO PRODUTO FORNECIDO';
ALTER TABLE FORNECEDORES_PRODUTOS CHANGE FRPR_FORNECEDOR FRPR_FORNECEDOR INT NOT NULL COMMENT 'CÓDIGO DO FORNECEDOR NO RELACIONAMENTO';
ALTER TABLE FORNECEDORES_PRODUTOS MODIFY FRPR_PRODUTOS INT NOT NULL COMMENT 'CÓDIGO DO PRODUTO NO RELACIONAMENTO';
ALTER TABLE FORNECEDORES_PRODUTOS DROP COLUMN FRPR_PRODUTOS COMMENT 'REMOVE O RELACIONAMENTO DIRETO COM PRODUTOS DO FORNECEDOR';
