CREATE SCHEMA ESTC_IV;
USE ESTC_IV;

CREATE TABLE IF NOT EXISTS CARGOS(
	ID_CARGO INT PRIMARY KEY,
    NOME_CARGO VARCHAR(50) NOT NULL,
    FUNCOES VARCHAR(100) NOT NULL,
    SALARIO DECIMAL(8,3)
);

CREATE TABLE IF NOT EXISTS TIPO_ENDERECO(
	COD_TIPO_END INT PRIMARY KEY,
    NOME_TIPO_END VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENDERECOS(
	ID_ENDERECO INT PRIMARY KEY,
    NOME_RUA VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PAIS VARCHAR(50) NOT NULL,
    CEP VARCHAR(8),
    TIPO_ENDERECO VARCHAR(50),
    CONSTRAINT FK_TIPO_ENDERECOS FOREIGN KEY (TIPO_ENDERECO) REFERENCES TIPO_ENDERECO(COD_TIPO_END)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
	NMR_MATRICULA INT PRIMARY KEY,
    NOME_FUNC VARCHAR(100),
    CPF_FUNC VARCHAR(14),
    DATA_ADMISS DATE NOT NULL,
    QUALIF_FUNC VARCHAR(45),
    CARGO INT,
    ENDERECO INT,
    CONSTRAINT FK_CARGO_EMPREGADOS FOREIGN KEY(CARGO) REFERENCES CARGOS(ID_CARGO),
    CONSTRAINT ENDERECOS_EMPREGADOS FOREIGN KEY(ENDERECO) REFERENCES ENDERECOS(ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS TELEFONES_EMPREGADOS(
	COD_TELEF_EMPG INT PRIMARY KEY,
    TLF_EMPG VARCHAR(11) NOT NULL,
    EMPREGADO INT,
    CONSTRAINT FK_EMPREGADOS_TELEFONES FOREIGN KEY (EMPREGADO) REFERENCES EMPREGADOS(NMR_MATRICULA)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	COD_PROD INT PRIMARY KEY,
    NOME_PROD VARCHAR(50) NOT NULL,
    DIMENSOES_PROD VARCHAR(30) NOT NULL,
    COR_PROD VARCHAR(30) NOT NULL,
    TEMP_FAB_PROD VARCHAR(30) NOT NULL,
    QNT_PROD_ESTQ INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPREGADOS_PRODUTOS(

);

