#CRIANDO O BANCO DE DADOS
CREATE SCHEMA EMPRESA_AEREA;

#USANDO O BANCO DE DADOS
USE EMPRESA_AEREA;


#--------------------TABELA DE PASSAGEIROS--------------------
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASS_CPF VARCHAR(14) PRIMARY KEY,
    PASS_NOME VARCHAR(50) NOT NULL,
    PASS_TELEFONE VARCHAR(15) NOT NULL,
    PASS_RUA VARCHAR(100) NOT NULL,
    PASS_NUMRUA INT,
    PASS_BAIRRO VARCHAR(50) NOT NULL,
    PASS_CIDADE VARCHAR(50) NOT NULL,
    PASS_ESTADO VARCHAR(50) NOT NULL,
    PASS_PAIS VARCHAR(50) NOT NULL,
    PASS_CODPOSTAL VARCHAR(10) NOT NULL,
    PASS_EMAIL VARCHAR(50) NOT NULL
);

#--------------------TABELA DE FUNCIONARIOS--------------------

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    FUNC_ID INT PRIMARY KEY,
    FUNC_CPF VARCHAR(14) NOT NULL,
    FUNC_NOME VARCHAR(50) NOT NULL,
    FUNC_DATANASC DATE NOT NULL,
    FUNC_RUA VARCHAR(100) NOT NULL,
    FUNC_NUMRUA INT,
    FUNC_BAIRRO VARCHAR(50) NOT NULL,
    FUNC_CIDADE VARCHAR(50) NOT NULL,
    FUNC_ESTADO VARCHAR(50) NOT NULL,
    FUNC_PAIS VARCHAR(50) NOT NULL,
    FUNC_CODPOSTAL VARCHAR(10) NOT NULL
);

#--------------------TABELA DE AERONAVES--------------------

CREATE TABLE IF NOT EXISTS AERONAVES (
    AERON_PREFIXO VARCHAR(10) PRIMARY KEY,
    AERON_MODELO VARCHAR(50) NOT NULL,
    AERON_FABRICANTE VARCHAR(50) NOT NULL,
    AERON_ANOFABR YEAR NOT NULL,
    AERON_CAPACIDADE TEXT NOT NULL,
    AERON_AUTONOMIA VARCHAR(10) NOT NULL
);

#--------------------TABELA DE AEROPORTOS--------------------

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    AEROP_CODIGO INT PRIMARY KEY,
    AEROP_NOME VARCHAR(50) NOT NULL,
    AEROP_CIDADE VARCHAR(50) NOT NULL,
    AEROP_PAIS VARCHAR(50) NOT NULL,
    AEROP_LATITUDE TEXT NOT NULL,
    AEROP_LONGITUDE TEXT NOT NULL
);

#--------------------TABELA DE VOOS--------------------

CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT PRIMARY KEY,
    VOO_DATA DATE NOT NULL,
    VOO_HORA TIME NOT NULL,
    VOO_AEROP_ORIGEM INT NOT NULL,
    VOO_AEROP_DESTINO INT NOT NULL,
    VOO_AERONAVE VARCHAR(10) NOT NULL,
    CONSTRAINT FK_AEROP_ORIGEM FOREIGN KEY(VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_CODIGO),
    CONSTRAINT FK_AEROP_DESTINO FOREIGN KEY(VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_CODIGO),
    CONSTRAINT FK_AERONAVE FOREIGN KEY(VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

#--------------------TABELA DE EQUIPES--------------------

CREATE TABLE IF NOT EXISTS EQUIPES (
    VOO_ID INT NOT NULL,
    FUNC_ID INT NOT NULL,
    PRIMARY KEY(VOO_ID, FUNC_ID),
    CONSTRAINT VOFU_FK_VOO FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID),
    CONSTRAINT VOFU_FK_FUNCIONARIO FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID)
);

#--------------------TABELA DE RESERVAS--------------------

CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_COD INT PRIMARY KEY,
    VOO_ID INT NOT NULL,
    PASS_CPF VARCHAR(14) NOT NULL,
    CONSTRAINT FK_PASSAGEIROS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
    CONSTRAINT FK_VOOS FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID)
);

#DDLS

ALTER TABLE PASSAGEIROS ADD PASS_DATA_NASCIMENTO DATE;
ALTER TABLE PASSAGEIROS MODIFY PASS_TELEFONE VARCHAR(20) NOT NULL; 
ALTER TABLE PASSAGEIROS CHANGE COLUMN PASS_RUA ENDERECO_PASS VARCHAR(100) NOT NULL;
DROP TABLE IF EXISTS PASSAGEIROS;
