CREATE SCHEMA ESTC_I;
USE ESTC_I;

#--------------------TABELA DE FORNECEDORES--------------------

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT NOT NULL,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

#--------------------TABELA DE FILIAIS--------------------

CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT NOT NULL,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL
);

#--------------------TABELA DE PRODUTOS--------------------

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

#--------------------TABELA DE PEDIDOS--------------------

CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL, #NOSSA CHAVE ESTRANGEIRA DE FORNECEDOR
#CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
#RESTRIÇÃO APELIDO CH.ESTRANGEIRA(CAMPO CRIADO) REFERENCIA TABELA(CH.PRIMÁRIA)
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA PRÁTICA
REFERENCES FORNECEDORES(FORNEC_COD) #REFERENCIA A CHAVE PRIMÁRIA DE FORNECEDORES
);

#--------------------TABELA DE RECEBIMENTOS--------------------

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

#--------------------ASSOCIATIVA ENTRE PEDIDOS E PRODUTOS--------------------

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS, PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#--------------------ASSOCIATIVA ENTRE FILIAIS E PRODUTOS--------------------

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#--------------------ASSOCIATIVA ENTRE FORNECEDORES E PRODUTOS--------------------

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

-- DDL'S PARA TABELA DE FORNECEDORES
ALTER TABLE FORNECEDORES ADD COLUMN FORNEC_EMAIL VARCHAR(50) COMMENT 'EMAIL DO FORNECEDOR';
ALTER TABLE FORNECEDORES CHANGE FORNEC_CONTATO FORNEC_CONTATO_TEXT TEXT NOT NULL COMMENT 'INFORMAÇÕES DE CONTATO DO FORNECEDOR';
ALTER TABLE FORNECEDORES MODIFY FORNEC_TELEFONE VARCHAR(20) COMMENT 'TELEFONE DO FORNECEDOR (FORMATO AUMENTADO)';
ALTER TABLE FORNECEDORES DROP COLUMN FORNEC_EMAIL COMMENT 'REMOVE A COLUNA DE EMAIL DO FORNECEDOR';

-- DDL'S PARA TABELA DE FILIAIS
ALTER TABLE FILIAIS ADD COLUMN FILIAL_EMAIL VARCHAR(50) COMMENT 'EMAIL DA FILIAL';
ALTER TABLE FILIAIS CHANGE FILIAL_CAPACIDADE FILIAL_CAPACIDADE_TEXT TEXT NOT NULL COMMENT 'CAPACIDADE DA FILIAL';
ALTER TABLE FILIAIS MODIFY FILIAL_NUMRUA INT NULL COMMENT 'NÚMERO DA RUA (OPCIONAL)';
ALTER TABLE FILIAIS DROP COLUMN FILIAL_EMAIL COMMENT 'REMOVE A COLUNA DE EMAIL DA FILIAL';

-- DDL'S PARA TABELA DE PRODUTOS
ALTER TABLE PRODUTOS ADD COLUMN PROD_CATEGORIA VARCHAR(30) COMMENT 'CATEGORIA DO PRODUTO';
ALTER TABLE PRODUTOS CHANGE PROD_DESCRICAO PROD_DESCRICAO_TEXT TEXT NOT NULL COMMENT 'DESCRIÇÃO DO PRODUTO';
ALTER TABLE PRODUTOS MODIFY PROD_PRECOUNIT DECIMAL(10,4) COMMENT 'PREÇO UNITÁRIO DO PRODUTO (COM MAIOR PRECISÃO)';
ALTER TABLE PRODUTOS DROP COLUMN PROD_CATEGORIA COMMENT 'REMOVE A COLUNA DE CATEGORIA DO PRODUTO';

-- DDL'S PARA TABELA DE PEDIDOS
ALTER TABLE PEDIDOS ADD COLUMN PED_FORNECEDOR_NOME VARCHAR(45) COMMENT 'NOME DO FORNECEDOR DO PEDIDO';
ALTER TABLE PEDIDOS CHANGE PED_PREVISAO PED_PREVISAO_ENTREGA DATE NOT NULL COMMENT 'DATA PREVISTA DE ENTREGA';
ALTER TABLE PEDIDOS MODIFY PED_DATA DATETIME COMMENT 'DATA E HORA DO PEDIDO';
ALTER TABLE PEDIDOS DROP COLUMN PED_FORNECEDOR_NOME COMMENT 'REMOVE A COLUNA DE NOME DO FORNECEDOR DO PEDIDO';

-- DDL'S PARA TABELA DE RECEBIMENTOS
ALTER TABLE RECEBIMENTOS ADD COLUMN RECEB_FORNECEDOR INT COMMENT 'CÓDIGO DO FORNECEDOR RELACIONADO';
ALTER TABLE RECEBIMENTOS CHANGE RECEB_QUANT_PROD RECEB_QUANTIDADE DECIMAL(10,3) COMMENT 'QUANTIDADE DE PRODUTOS RECEBIDOS';
ALTER TABLE RECEBIMENTOS MODIFY RECEB_PEDIDOS INT NOT NULL COMMENT 'ID DO PEDIDO RELACIONADO';
ALTER TABLE RECEBIMENTOS DROP COLUMN RECEB_FORNECEDOR COMMENT 'REMOVE A COLUNA DE CÓDIGO DO FORNECEDOR RELACIONADO';

-- DDL'S PARA TABELA DE PEDIDOS_PRODUTOS
ALTER TABLE PEDIDOS_PRODUTOS ADD COLUMN PDPR_PRECO DECIMAL(10,2) COMMENT 'PREÇO DO PRODUTO NO PEDIDO';
ALTER TABLE PEDIDOS_PRODUTOS CHANGE PDPR_QUANT PDPR_QUANTIDADE DECIMAL(10,3) NOT NULL COMMENT 'QUANTIDADE DE PRODUTOS NO PEDIDO';
ALTER TABLE PEDIDOS_PRODUTOS MODIFY PDPR_PEDIDOS INT NOT NULL COMMENT 'ID DO PEDIDO RELACIONADO';
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN PDPR_PRECO COMMENT 'REMOVE A COLUNA DE PREÇO DO PRODUTO NO PEDIDO';

-- DDL'S PARA TABELA DE FILIAIS_PRODUTOS
ALTER TABLE FILIAIS_PRODUTOS ADD COLUMN FLPR_PRECO DECIMAL(10,2) COMMENT 'PREÇO DO PRODUTO NA FILIAL';
ALTER TABLE FILIAIS_PRODUTOS CHANGE FLPR_QUANT FLPR_QUANTIDADE DECIMAL(10,3) NOT NULL COMMENT 'QUANTIDADE DO PRODUTO NA FILIAL';
ALTER TABLE FILIAIS_PRODUTOS MODIFY FLPR_FILIAL INT NOT NULL COMMENT 'ID DA FILIAL RELACIONADA';
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN FLPR_PRECO COMMENT 'REMOVE A COLUNA DE PREÇO DO PRODUTO NA FILIAL';

-- DDL'S PARA TABELA DE FORNECEDORES_PRODUTOS
ALTER TABLE FORNECEDORES_PRODUTOS ADD COLUMN FRPR_PRECO DECIMAL(10,2) COMMENT 'PREÇO DO PRODUTO OFERECIDO PELO FORNECEDOR';
ALTER TABLE FORNECEDORES_PRODUTOS CHANGE FRPR_FORNECEDOR FRPR_COD_FORNECEDOR INT NOT NULL COMMENT 'CÓDIGO DO FORNECEDOR';
ALTER TABLE FORNECEDORES_PRODUTOS MODIFY FRPR_PRODUTOS INT NOT NULL COMMENT 'ID DO PRODUTO RELACIONADO';
ALTER TABLE FORNECEDORES_PRODUTOS DROP COLUMN FRPR_PRECO COMMENT 'REMOVE A COLUNA DE PREÇO DO PRODUTO OFERECIDO PELO FORNECEDOR';

