CREATE SCHEMA ESTC_III;
USE ESTC_III;

CREATE TABLE IF NOT EXISTS CARGOS(
    ID_CARGO INT PRIMARY KEY,
    NOME_CARGO VARCHAR(50) NOT NULL,
    FUNCOES VARCHAR(100) NOT NULL,
    SALARIO DECIMAL(8,3)
);

CREATE TABLE IF NOT EXISTS TIPO_ENDERECO(
    COD_TIPO_END INT PRIMARY KEY,
    NOME_TIPO_END VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENDERECOS(
    ID_ENDERECO INT PRIMARY KEY,
    NOME_RUA VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PAIS VARCHAR(50) NOT NULL,
    CEP VARCHAR(8),
    TIPO_ENDERECO INT NOT NULL,
    CONSTRAINT FK_TIPO_ENDERECOS_ENDERECOS FOREIGN KEY (TIPO_ENDERECO) REFERENCES TIPO_ENDERECO(COD_TIPO_END)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
    NMR_MATRICULA INT PRIMARY KEY,
    NOME_FUNC VARCHAR(100),
    CPF_FUNC VARCHAR(14),
    DATA_ADMISS DATE NOT NULL,
    QUALIF_FUNC VARCHAR(45),
    CARGO INT NOT NULL,
    ENDERECO INT,
    CONSTRAINT FK_CARGO_EMPREGADOS FOREIGN KEY(CARGO) REFERENCES CARGOS(ID_CARGO),
    CONSTRAINT FK_ENDERECOS_EMPREGADOS FOREIGN KEY(ENDERECO) REFERENCES ENDERECOS(ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS TELEFONES_EMPREGADOS(
    COD_TELEF_EMPG INT PRIMARY KEY,
    TLF_EMPG VARCHAR(11) NOT NULL,
    EMPREGADO INT NOT NULL,
    CONSTRAINT FK_EMPREGADOS_TELEFONES FOREIGN KEY (EMPREGADO) REFERENCES EMPREGADOS(NMR_MATRICULA)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
    COD_PROD INT PRIMARY KEY,
    NOME_PROD VARCHAR(50) NOT NULL,
    DIMENSOES_PROD VARCHAR(30) NOT NULL,
    COR_PROD VARCHAR(30) NOT NULL,
    TEMP_FAB_PROD VARCHAR(30) NOT NULL,
    QNT_PROD_ESTQ INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPREGADOS_PRODUTOS(
    PRODUTO INT,
    FUNCIONARIO INT,
    HORAS_TRABALHADAS VARCHAR(4) NOT NULL,
    PRIMARY KEY(PRODUTO, FUNCIONARIO),
    CONSTRAINT FK_PRODUTO_EMPREGADOS FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(COD_PROD),
    CONSTRAINT FK_FUNCIONARIO_EMPREGADOS FOREIGN KEY(FUNCIONARIO) REFERENCES EMPREGADOS(NMR_MATRICULA)
);

CREATE TABLE IF NOT EXISTS MAQUINAS(
    MAQ_COD INT PRIMARY KEY,
    MAQ_NOME VARCHAR(50) NOT NULL,
    MAQ_TEMPO_VIDA VARCHAR(5) NOT NULL,
    MAR_DATA_COMPRA DATE NOT NULL,
    MAQ_DATA_FIM_GART DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS MAQUINAS_PRODUTOS(
    MAQUINA INT,
    PRODUTO_UTLZ INT,
    HORAS_UTLZ VARCHAR(5) NOT NULL,
    PRIMARY KEY(MAQUINA, PRODUTO_UTLZ),
    CONSTRAINT FK_MAQUINA_MAQUINAS_PRODUTOS FOREIGN KEY (MAQUINA) REFERENCES MAQUINAS(MAQ_COD),
    CONSTRAINT FK_PRODUTO_MAQUINAS_PRODUTOS FOREIGN KEY (PRODUTO_UTLZ) REFERENCES PRODUTO(COD_PROD)
);

CREATE TABLE IF NOT EXISTS REGISTRO_MANUTENCAO(
    RM_COD INT PRIMARY KEY,
    RM_DATA DATE NOT NULL,
    RM_DESC TEXT NOT NULL,
    RM_MAQUINA INT NOT NULL,
    CONSTRAINT FK_MAQUINA_REGISTRO_MANUTENCAO FOREIGN KEY (RM_MAQUINA) REFERENCES MAQUINAS(MAQ_COD)
);

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTE(
    TPDC_COD INT PRIMARY KEY,
    TPDC_NOME VARCHAR(50) NOT NULL,
    TDCP_QNT_ESTQ DECIMAL(10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPONENTES(
    COMP_COD INT PRIMARY KEY,
    COMP_NOME VARCHAR(50) NOT NULL,
    COMP_UNIDADE VARCHAR(30) NOT NULL,
    COMP_QNT_ESTQ DECIMAL(10,3) NOT NULL,
    COMP_TIPO INT NOT NULL,
    CONSTRAINT FK_TIPO_COMPONENTE FOREIGN KEY(COMP_TIPO) REFERENCES TIPO_COMPONENTE(TPDC_COD)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_COMPONENTES(
    COMPONENTE INT,
    PROD_PRDZ INT,
    PRIMARY KEY(COMPONENTE, PROD_PRDZ),
    CONSTRAINT FK_COMPONENTE_PRODUTOS FOREIGN KEY(COMPONENTE) REFERENCES COMPONENTES(COMP_COD),
    CONSTRAINT FK_PRODUTO_PRODUTOS FOREIGN KEY(PROD_PRDZ) REFERENCES PRODUTO(COD_PROD)
);

CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS(
    RE_ID INT PRIMARY KEY,
    RE_HORAS_MAO_OBRA VARCHAR(5) NOT NULL,
    RE_DATA DATE NOT NULL,
    RE_TEMPO_MAQ VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPRESAS(
    EMPRESA_CNPJ VARCHAR(14) PRIMARY KEY,
    EMPRESA_RAZAO_SOCIAL VARCHAR(50) NOT NULL,
    EMPRESA_RAMO VARCHAR(50) NOT NULL,
    EMPRESA_CONT VARCHAR(14) NOT NULL,
    EMPRESA_END INT NOT NULL,
    CONSTRAINT FK_ENDERECOS_EMPRESAS FOREIGN KEY(EMPRESA_END) REFERENCES ENDERECOS(ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS TELEFONES_EMPRESAS(
    ID_TELF_EMP INT PRIMARY KEY,
    EMPRESA VARCHAR(14),
    TELEFONE VARCHAR(14) NOT NULL,
    CONSTRAINT FK_EMPRESAS_TELEFONES_EMPRESAS FOREIGN KEY(EMPRESA) REFERENCES EMPRESAS(EMPRESA_CNPJ)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    FORN_ID INT PRIMARY KEY,
    CONT_PESSOA VARCHAR(50) NOT NULL,
    FORN_NMR VARCHAR(14) NOT NULL,
    FORN_CNPJ VARCHAR(14) NOT NULL,
    FORN_ENDERECO INT NOT NULL,
    CONSTRAINT FK_EMPRESAS_FORNECEDORES FOREIGN KEY (FORN_CNPJ) REFERENCES EMPRESAS(EMPRESA_CNPJ),
    CONSTRAINT FK_ENDERECOS_FORNECEDORES FOREIGN KEY (FORN_ENDERECO) REFERENCES ENDERECOS(ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS COMPONENTES_FORNECEDORES(
    COMPONENTE INT,
    FORNECEDOR_COMP INT,
    PRECO_UNT DECIMAL(8,3) NOT NULL,
    CONSTRAINT FK_COMPONENTE_COMPONENTES_FORNECEDORES FOREIGN KEY (COMPONENTE) REFERENCES COMPONENTES(COMP_COD),
    CONSTRAINT FK_FORNECEDOR_COMPONENTES_FORNECEDORES FOREIGN KEY (FORNECEDOR_COMP) REFERENCES FORNECEDORES(FORN_ID)
);

CREATE TABLE IF NOT EXISTS REGISTRO_RESSUPRIMENTO(
    RS_COD INT PRIMARY KEY,
    RS_DATA DATE NOT NULL,
    RS_QNT_NECES DECIMAL(8,3) NOT NULL,
    RS_COMP INT NOT NULL,
    RS_FORN INT NOT NULL, 
    CONSTRAINT FK_COMPONENTE_REGISTRO_RESSUPRIMENTO FOREIGN KEY (RS_COMP) REFERENCES COMPONENTES(COMP_COD),
    CONSTRAINT FK_FORNECEDOR_REGISTRO_RESSUPRIMENTO FOREIGN KEY (RS_FORN) REFERENCES FORNECEDORES(FORN_ID)
);

CREATE TABLE IF NOT EXISTS ENDERECOS_CLIENTES(
    ID_ENDERECOS_CLT INT PRIMARY KEY,
    RUA VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PAIS VARCHAR(50) NOT NULL,
    CEP VARCHAR(8),
    TIPO_ENDERECO INT,
    CONSTRAINT FK_TIPO_ENDERECOS_ENDERECOS_CLIENTES FOREIGN KEY (TIPO_ENDERECO) REFERENCES TIPO_ENDERECO(COD_TIPO_END)
);

CREATE TABLE IF NOT EXISTS CLIENTES(
    CLT_COD INT PRIMARY KEY,
    CLT_DATA_CADS DATE NOT NULL,
    CLT_PESS_CONT VARCHAR(50) NOT NULL,
    CLT_NMR_CONT VARCHAR(14) NOT NULL,
    CLT_CNPJ VARCHAR(14) NOT NULL,
    CONSTRAINT FK_EMPRESAS_CLIENTES FOREIGN KEY (CLT_CNPJ) REFERENCES EMPRESAS(EMPRESA_CNPJ)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS(
    ENCOM_COD INT PRIMARY KEY,
    ENCOM_DATA DATE NOT NULL,
    ENCOM_CLT INT NOT NULL,
    CONSTRAINT FK_CLIENTES_ENCOMENDAS FOREIGN KEY (ENCOM_CLT) REFERENCES CLIENTES(CLT_COD)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
    PAG_COD INT PRIMARY KEY,
    PAG_VLR_TOTAL DECIMAL(10,3) NOT NULL,
    PAG_VLR_DESC DECIMAL(10,3) NOT NULL,
    PAG_DATA DATE NOT NULL,
    PAG_QNT_PARCELAS INT NOT NULL,
    PAG_ENCOM INT NOT NULL,
    CONSTRAINT FK_ENCOMENDAS_PAGAMENTOS FOREIGN KEY (PAG_ENCOM) REFERENCES ENCOMENDAS(ENCOM_COD)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_ENCOMENDAS(
    ENCM_COD INT NOT NULL,
    PROD_COD INT NOT NULL,
    QNT_PROD INT NOT NULL,
    PRIMARY KEY (ENCM_COD, PROD_COD),
    CONSTRAINT FK_ENCOMENDAS_PRODUTOS FOREIGN KEY (ENCM_COD) REFERENCES ENCOMENDAS(ENCOM_COD),
    CONSTRAINT FK_PRODUTOS_PRODUTOS_ENCOMENDAS FOREIGN KEY (PROD_COD) REFERENCES PRODUTO(COD_PROD)
);

ALTER TABLE CLIENTES ADD COLUMN EMAIL VARCHAR(100);
DROP TABLE IF EXISTS TELEFONES_EMPREGADOS;
ALTER TABLE CARGOS MODIFY SALARIO DECIMAL(10, 2);
ALTER TABLE EMPREGADOS CHANGE NOME_FUNC NOME_EMPREGADO VARCHAR(100);
