CREATE SCHEMA EMPRESA_AEREA;

USE EMPRESA_AEREA;

CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASS_CPF VARCHAR(14) PRIMARY KEY,
    PASS_NOME VARCHAR(50) NOT NULL,
    PASS_TELEFONE VARCHAR(15) NOT NULL,
    PASS_RUA VARCHAR(100) NOT NULL,
    PASS_NUMRUA INT,
    PASS_BAIRRO VARCHAR(50) NOT NULL,
    PASS_CIDADE VARCHAR(50) NOT NULL,
    PASS_ESTADO VARCHAR(50) NOT NULL,
    PASS_PAIS VARCHAR(50) NOT NULL,
    PASS_CODPOSTAL VARCHAR(10) NOT NULL,
    PASS_EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    FUNC_ID INT PRIMARY KEY,
    FUNC_CPF VARCHAR(14) NOT NULL,
    FUNC_NOME VARCHAR(50) NOT NULL,
    FUNC_DATANASC DATE NOT NULL,
    FUNC_RUA VARCHAR(100) NOT NULL,
    FUNC_NUMRUA INT,
    FUNC_BAIRRO VARCHAR(50) NOT NULL,
    FUNC_CIDADE VARCHAR(50) NOT NULL,
    FUNC_ESTADO VARCHAR(50) NOT NULL,
    FUNC_PAIS VARCHAR(50) NOT NULL,
    FUNC_CODPOSTAL VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS AERONAVES (
    AERON_PREFIXO VARCHAR(10) PRIMARY KEY,
    AERON_MODELO VARCHAR(50) NOT NULL,
    AERON_FABRICANTE VARCHAR(50) NOT NULL,
    AERON_ANOFABR YEAR NOT NULL,
    AERON_CAPACIDADE TEXT NOT NULL,
    AERON_AUTONOMIA VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    AEROP_CODIGO INT PRIMARY KEY,
    AEROP_NOME VARCHAR(50) NOT NULL,
    AEROP_CIDADE VARCHAR(50) NOT NULL,
    AEROP_PAIS VARCHAR(50) NOT NULL,
    AEROP_LATITUDE TEXT NOT NULL,
    AEROP_LONGITUDE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT PRIMARY KEY,
    VOO_DATA DATE NOT NULL,
    VOO_HORA TIME NOT NULL,
    VOO_AEROP_ORIGEM INT NOT NULL,
    VOO_AEROP_DESTINO INT NOT NULL,
    VOO_AERONAVE VARCHAR(10) NOT NULL,
    CONSTRAINT FK_AEROP_ORIGEM FOREIGN KEY(VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_CODIGO),
    CONSTRAINT FK_AEROP_DESTINO FOREIGN KEY(VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_CODIGO),
    CONSTRAINT FK_AERONAVE FOREIGN KEY(VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

CREATE TABLE IF NOT EXISTS EQUIPES (
    VOO_ID INT NOT NULL,
    FUNC_ID INT NOT NULL,
    PRIMARY KEY(VOO_ID, FUNC_ID),
    CONSTRAINT VOFU_FK_VOO FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID),
    CONSTRAINT VOFU_FK_FUNCIONARIO FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID)
);

CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_COD INT PRIMARY KEY,
    VOO_ID INT NOT NULL,
    PASS_CPF VARCHAR(14) NOT NULL,
    CONSTRAINT FK_PASSAGEIROS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
    CONSTRAINT FK_VOOS FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID)
);

-- DDL'S PARA TABELA DE PASSAGEIROS
ALTER TABLE PASSAGEIROS ADD COLUMN PASS_NACIONALIDADE VARCHAR(50) COMMENT 'NACIONALIDADE DO PASSAGEIRO';
ALTER TABLE PASSAGEIROS CHANGE PASS_NOME PASS_NOME VARCHAR(100) NOT NULL COMMENT 'NOME COMPLETO DO PASSAGEIRO';
ALTER TABLE PASSAGEIROS MODIFY PASS_TELEFONE VARCHAR(20) COMMENT 'TELEFONE DO PASSAGEIRO';
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_CODPOSTAL COMMENT 'REMOVE A COLUNA DE CÓDIGO POSTAL DO PASSAGEIRO';

-- DDL'S PARA TABELA DE FUNCIONARIOS
ALTER TABLE FUNCIONARIOS ADD COLUMN FUNC_EMAIL VARCHAR(50) COMMENT 'EMAIL DO FUNCIONÁRIO';
ALTER TABLE FUNCIONARIOS CHANGE FUNC_NOME FUNC_NOME VARCHAR(100) NOT NULL COMMENT 'NOME COMPLETO DO FUNCIONÁRIO';
ALTER TABLE FUNCIONARIOS MODIFY FUNC_CPF VARCHAR(20) NOT NULL COMMENT 'CPF DO FUNCIONÁRIO';
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_CODPOSTAL COMMENT 'REMOVE A COLUNA DE CÓDIGO POSTAL DO FUNCIONÁRIO';

-- DDL'S PARA TABELA DE AERONAVES
ALTER TABLE AERONAVES ADD COLUMN AERON_TIPO VARCHAR(50) COMMENT 'TIPO DA AERONAVE (PASSAGEIRO OU CARGA)';
ALTER TABLE AERONAVES CHANGE AERON_MODELO AERON_MODELO VARCHAR(100) NOT NULL COMMENT 'MODELO DA AERONAVE';
ALTER TABLE AERONAVES MODIFY AERON_CAPACIDADE INT COMMENT 'CAPACIDADE DA AERONAVE EM PASSAGEIROS';
ALTER TABLE AERONAVES DROP COLUMN AERON_ANOFABR COMMENT 'REMOVE A COLUNA DE ANO DE FABRICAÇÃO DA AERONAVE';

-- DDL'S PARA TABELA DE AEROPORTOS
ALTER TABLE AEROPORTOS ADD COLUMN AEROP_TIPO VARCHAR(50) COMMENT 'TIPO DE AEROPORTO (NACIONAL OU INTERNACIONAL)';
ALTER TABLE AEROPORTOS CHANGE AEROP_CIDADE AEROP_CIDADE VARCHAR(100) NOT NULL COMMENT 'CIDADE DO AEROPORTO';
ALTER TABLE AEROPORTOS MODIFY AEROP_LATITUDE VARCHAR(20) COMMENT 'LATITUDE DO AEROPORTO';
ALTER TABLE AEROPORTOS DROP COLUMN AEROP_LONGITUDE COMMENT 'REMOVE A COLUNA DE LONGITUDE DO AEROPORTO';

-- DDL'S PARA TABELA DE VOOS
ALTER TABLE VOOS ADD COLUMN VOO_DURACAO TIME COMMENT 'DURAÇÃO DO VOO';
ALTER TABLE VOOS CHANGE VOO_HORA VOO_HORA TIME NOT NULL COMMENT 'HORA DE PARTIDA DO VOO';
ALTER TABLE VOOS MODIFY VOO_AERONAVE VARCHAR(15) COMMENT 'CÓDIGO DA AERONAVE NO VOO';
ALTER TABLE VOOS DROP COLUMN VOO_AEROP_DESTINO COMMENT 'REMOVE A COLUNA DE DESTINO DO VOO';

-- DDL'S PARA TABELA DE EQUIPES
ALTER TABLE EQUIPES ADD COLUMN EQUIPE_FUNCAO VARCHAR(50) COMMENT 'FUNÇÃO DO FUNCIONÁRIO NA EQUIPE';
ALTER TABLE EQUIPES CHANGE VOO_ID VOO_ID INT NOT NULL COMMENT 'ID DO VOO NA EQUIPE';
ALTER TABLE EQUIPES MODIFY FUNC_ID INT NOT NULL COMMENT 'ID DO FUNCIONÁRIO NA EQUIPE';
ALTER TABLE EQUIPES DROP COLUMN EQUIPE_FUNCAO COMMENT 'REMOVE A COLUNA DE FUNÇÃO DA EQUIPE';

-- DDL'S PARA TABELA DE RESERVAS
ALTER TABLE RESERVAS ADD COLUMN RESERVA_STATUS ENUM('CONFIRMADA', 'CANCELADA', 'PENDENTE') COMMENT 'STATUS DA RESERVA';
ALTER TABLE RESERVAS CHANGE PASS_CPF PASS_CPF VARCHAR(20) NOT NULL COMMENT 'CPF DO PASSAGEIRO';
ALTER TABLE RESERVAS MODIFY VOO_ID INT NOT NULL COMMENT 'ID DO VOO NA RESERVA';
ALTER TABLE RESERVAS DROP COLUMN RESERVA_COD COMMENT 'REMOVE A COLUNA DE CÓDIGO DA RESERVA';
